In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/weather_data - weather_data.csv')
df['day'] = pd.to_datetime(df['day'], errors='coerce')
df['day_name'] = df['day'].dt.day_name()
df

          day  temperature  windspeed   event
0  01-01-2017         32.0        6.0    Rain
1  02-01-2017          NaN        9.0   Sunny
2  03-01-2017         28.0        NaN    Snow
3  04-01-2017          NaN        7.0     NaN
4  05-01-2017         32.0        NaN    Rain
5  06-01-2017          NaN        NaN   Sunny
6  07-01-2017          NaN        NaN     NaN
7  08-01-2017         34.0        8.0  Cloudy
8  09-01-2017         40.0       12.0   Sunny

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          9 non-null      object
 1   temperature  5 non-null      float64
 2   windspeed    5 non-null      float64
 3   event        7 non-null      object
dtypes: float64(2), object(2)
memory usage: 420.0+ bytes

In [4]:
df.describe()

       temperature  windspeed
count      5.00000   5.000000
mean      33.20000   8.400000
std        4.38178   2.302173
min       28.00000   6.000000
25%       32.00000   7.000000
50%       32.00000   8.000000
75%       34.00000   9.000000
max       40.00000  12.000000

In [5]:
df.isnull().sum()

day            0
temperature    4
windspeed      4
event          2
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

Replacing Null Values with some meaning full information

In [7]:
df['temperature'] = df['temperature'].fillna(df['temperature'].mean())

In [8]:
df.isnull().sum()

day            0
temperature    0
windspeed      4
event          2
dtype: int64

In [9]:
df['windspeed'] = df['windspeed'].fillna(df['windspeed'].mean())

In [10]:
df['event'].value_counts()

event
Sunny     3
Rain      2
Snow      1
Cloudy    1
Name: count, dtype: int64

Replacing NaN values in event as Sunny cause it has more count

In [11]:
df['event']=df['event'].fillna('Sunny')

In [12]:
df

          day  temperature  windspeed   event
0  01-01-2017         32.0        6.0    Rain
1  02-01-2017         33.2        9.0   Sunny
2  03-01-2017         28.0        8.4    Snow
3  04-01-2017         33.2        7.0   Sunny
4  05-01-2017         32.0        8.4    Rain
5  06-01-2017         33.2        8.4   Sunny
6  07-01-2017         33.2        8.4   Sunny
7  08-01-2017         34.0        8.0  Cloudy
8  09-01-2017         40.0       12.0   Sunny

In [64]:
df['day'] = pd.to_datetime(df['day'],errors='coerce')

In [70]:
df['day'] = pd.to_datetime(df['day'], errors='coerce')
df['day_name'] = df['day'].dt.day_name()

In [66]:
df

        day  temperature  windspeed   event
0  Thursday         32.0        6.0    Rain
1  Thursday         33.2        9.0   Sunny
2  Thursday         28.0        8.4    Snow
3  Thursday         33.2        7.0   Sunny
4  Thursday         32.0        8.4    Rain
5  Thursday         33.2        8.4   Sunny
6  Thursday         33.2        8.4   Sunny
7  Thursday         34.0        8.0  Cloudy
8  Thursday         40.0       12.0   Sunny

In [ ]:
display(df.head())
display(df.dtypes)

In [13]:
df2 = pd.read_csv('/content/weather_data_replace_regex - weather_data_replace_regex.csv')
df2.head()

          day temperature windspeed  event
0  01-01-2017          32         6   Rain
1  01-02-2017      -99999       7km  Sunny
2  01-03-2017          28    -99999   Snow
3  01-04-2017      -99999         7      0
4  01-05-2017         32C    -99999   Rain

In [18]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          7 non-null      object
 1   temperature  7 non-null      object
 2   windspeed    7 non-null      object
 3   event        7 non-null      object
dtypes: object(4)
memory usage: 356.0+ bytes

In [19]:
df2.describe()

               day temperature windspeed event
count            7           7         7     7
unique           6           6         6     4
top     01-06-2017      -99999    -99999  Rain
freq             2           2         2     2

In [20]:
df2.value_counts().sum()

np.int64(7)

In [21]:
df2.isnull().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [31]:
df2.duplicated().sum()

np.int64(0)

In [22]:
df2['day'].unique()

array(['01-01-2017', '01-02-2017', '01-03-2017', '01-04-2017',
       '01-05-2017', '01-06-2017'], dtype=object)

In [23]:
df2['temperature'].unique()

array(['32', '-99999', '28', '32C', '31', '34'], dtype=object)

In [26]:
df2['windspeed'].unique()

array(['6', '7km', '-99999', '7', '2', '5MPH'], dtype=object)

In [27]:
df2['day'].value_counts()

day
01-06-2017    2
01-01-2017    1
01-02-2017    1
01-03-2017    1
01-04-2017    1
01-05-2017    1
Name: count, dtype: int64

In [28]:
df2['windspeed'].value_counts()

windspeed
-99999    2
6         1
7km       1
7         1
2         1
5MPH      1
Name: count, dtype: int64

In [29]:
df2['event'].value_counts()

event
Rain     2
Sunny    2
0        2
Snow     1
Name: count, dtype: int64

Removing MPH and km in windspeed

In [30]:
df2.dtypes

day            object
temperature    object
windspeed      object
event          object
dtype: object

Temperature and windspeed has wrong data-types so making it float but first clean the data

In [37]:
df2['windspeed'] = df2['windspeed'].str.replace(r'MPH|km', '', regex=True)

In [39]:
df2['windspeed']

0         6
1         7
2    -99999
3         7
4    -99999
5         2
6         5
Name: windspeed, dtype: object

In [41]:
df2['windspeed'] = df2['windspeed'].replace('-99999', np.nan)
df2['windspeed'] = df2['windspeed'].astype(float)

In [45]:
df2['temperature'] = df2['temperature'].astype(str).str.replace('C', '')
df2['temperature'] = df2['temperature'].replace('-99999', np.nan)
df2['temperature'] = df2['temperature'].astype(float)

In [43]:
df2

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017          NaN        7.0  Sunny
2  01-03-2017         28.0        NaN   Snow
3  01-04-2017          NaN        7.0      0
4  01-05-2017         32.0        NaN   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-06-2017         34.0        5.0      0

In [44]:
df2.dtypes

day             object
temperature    float64
windspeed      float64
event           object
dtype: object

In [46]:
df2['event'] = df2['event'].replace('0', 'Sunny')
display(df2['event'].value_counts())

event
Sunny    4
Rain     2
Snow     1
Name: count, dtype: int64

In [68]:
df2.isnull().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [51]:
df2['windspeed'] = df2['windspeed'].fillna(df2['windspeed'].mean())

In [52]:
df2['temperature'] = df2['temperature'].fillna(df2['temperature'].mean())

In [53]:
df2.isnull().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [54]:
df2

          day  temperature  windspeed  event
0  01-01-2017         32.0        6.0   Rain
1  01-02-2017         31.4        7.0  Sunny
2  01-03-2017         28.0        5.4   Snow
3  01-04-2017         31.4        7.0  Sunny
4  01-05-2017         32.0        5.4   Rain
5  01-06-2017         31.0        2.0  Sunny
6  01-06-2017         34.0        5.0  Sunny

changing day data-type to day

In [57]:
df2['day'] = pd.to_datetime(df2['day'],errors='coerce')

In [58]:
df2.dtypes

day            datetime64[ns]
temperature           float64
windspeed             float64
event                  object
dtype: object

In [73]:
df2['day'] = pd.to_datetime(df2['day'], errors='coerce')
df2['day_name'] = df2['day'].dt.day_name()

In [74]:
df2

         day  temperature  windspeed  event   day_name
0 2017-01-01         32.0        6.0   Rain     Sunday
1 2017-01-02         31.4        7.0  Sunny     Monday
2 2017-01-03         28.0        5.4   Snow    Tuesday
3 2017-01-04         31.4        7.0  Sunny  Wednesday
4 2017-01-05         32.0        5.4   Rain   Thursday
5 2017-01-06         31.0        2.0  Sunny     Friday
6 2017-01-06         34.0        5.0  Sunny     Friday