In [1]:
import numpy as np
import pandas as pd

In [3]:
data = {
    'Category':['A','B','A','B','A','B','A','B'],
    'Store':['s1','s1','s2','s2','s1','s2','s2','s1'],
    'Sales':[100,200,150,250,120,180,200,300],
    'Quantity':[10,15,12,18,8,20,15,25],
    'Date':pd.date_range('2023-01-01',periods=8)
}
df = pd.DataFrame(data)

In [4]:
df

  Category Store  Sales  Quantity       Date
0        A    s1    100        10 2023-01-01
1        B    s1    200        15 2023-01-02
2        A    s2    150        12 2023-01-03
3        B    s2    250        18 2023-01-04
4        A    s1    120         8 2023-01-05
5        B    s2    180        20 2023-01-06
6        A    s2    200        15 2023-01-07
7        B    s1    300        25 2023-01-08

In [6]:
cat_sales_sum = df.groupby('Category')['Sales'].sum()
cat_sales_sum

Category
A    570
B    930
Name: Sales, dtype: int64

In [7]:
sto_sales_sum = df.groupby('Store')['Sales'].sum()
sto_sales_sum

Store
s1    720
s2    780
Name: Sales, dtype: int64

In [9]:
multi_sales_sum = df.groupby(['Category','Store'])['Sales'].sum()
multi_sales_sum

Category  Store
A         s1       220
          s2       350
B         s1       500
          s2       430
Name: Sales, dtype: int64

In [10]:
multi_sales_df = multi_sales_sum.reset_index()
multi_sales_df

  Category Store  Sales
0        A    s1    220
1        A    s2    350
2        B    s1    500
3        B    s2    430

In [11]:
df['Sales'].agg(['mean','median','min','max','std','count','var'])

mean       187.500000
median     190.000000
min        100.000000
max        300.000000
std         66.062741
count        8.000000
var       4364.285714
Name: Sales, dtype: float64

In [13]:
grouped_agg = df.groupby('Category').agg({
    'Sales':['sum','max'],
    'Quantity':['mean','median']
})

grouped_agg

         Sales      Quantity
           sum  max     mean median
Category
A          570  200    11.25   11.0
B          930  300    19.50   19.0

In [18]:
import pandas as pd

employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [19]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [20]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [21]:
pd.merge(employees,salaries,on='employee_id',how='outer')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

In [22]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN

In [23]:
pd.merge(employees,salaries,on='employee_id',how='right')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000
3            6    NaN        NaN   70000   8000
4            7    NaN        NaN   90000  12000

In [26]:
df1 = pd.DataFrame({
    'A':['A0','A1','A2'],
    'B':['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A':['A3','A4','A5'],
    'B':['B3','B4','B5'],
    'C':['C3','C4','C5']
})

In [28]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [29]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

In [31]:
import pandas as pd

df_a = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

df_b = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[4, 5, 6])

In [32]:
df_a.join(df_b)

      name  score
1    Alice    NaN
2      Bob    NaN
3  Charlie    NaN

In [33]:
df_a.join(df_b,how='inner')

Empty DataFrame
Columns: [name, score]
Index: []

In [34]:
df_a.join(df_b,how='outer')

      name  score
1    Alice    NaN
2      Bob    NaN
3  Charlie    NaN
4      NaN   85.0
5      NaN   90.0
6      NaN   75.0

In [37]:
data ={
    'Date':pd.date_range('2023-01-01',periods=20),
    'Product':['A','B','C','D']*5,
    'Region':['East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South','East','West','North','South'],
    'Sales':np.random.randint(100,1000,20),
    'Units':np.random.randint(10,100,20),
    'Rep':['John','Marry','Bob','Alice','John','Marry','Bob','Alice','John','Marry','Bob','Alice','John','Marry','Bob','Alice','John','Marry','Bob','Alice']
}
df = pd.DataFrame(data)
df

         Date Product Region  Sales  Units    Rep
0  2023-01-01       A   East    263     86   John
1  2023-01-02       B   West    849     56  Marry
2  2023-01-03       C  North    670     16    Bob
3  2023-01-04       D  South    391     90  Alice
4  2023-01-05       A   East    607     92   John
5  2023-01-06       B   West    208     37  Marry
6  2023-01-07       C  North    385     12    Bob
7  2023-01-08       D  South    561     15  Alice
8  2023-01-09       A   East    211     90   John
9  2023-01-10       B   West    163     35  Marry
10 2023-01-11       C  North    523     90    Bob
11 2023-01-12       D  South    344     65  Alice
12 2023-01-13       A   East    171     75   John
13 2023-01-14       B   West    522     43  Marry
14 2023-01-15       C  North    350     26    Bob
15 2023-01-16       D  South    460     72  Alice
16 2023-01-17       A   East    682     79   John
17 2023-01-18       B   West    467     70  Marry
18 2023-01-19       C  North    649     58    Bob
19 2023-01-20       D  South    158     94  Alice

In [38]:
df['Month']=df['Date'].dt.month_name()
df['Quarter']='Q'+df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    263     86   John  January      Q1
1  2023-01-02       B   West    849     56  Marry  January      Q1
2  2023-01-03       C  North    670     16    Bob  January      Q1
3  2023-01-04       D  South    391     90  Alice  January      Q1
4  2023-01-05       A   East    607     92   John  January      Q1
5  2023-01-06       B   West    208     37  Marry  January      Q1
6  2023-01-07       C  North    385     12    Bob  January      Q1
7  2023-01-08       D  South    561     15  Alice  January      Q1
8  2023-01-09       A   East    211     90   John  January      Q1
9  2023-01-10       B   West    163     35  Marry  January      Q1
10 2023-01-11       C  North    523     90    Bob  January      Q1
11 2023-01-12       D  South    344     65  Alice  January      Q1
12 2023-01-13       A   East    171     75   John  January      Q1
13 2023-01-14       B   West    522     43  Marry  January      Q1
14 2023-01-15       C  North    350     26    Bob  January      Q1
15 2023-01-16       D  South    460     72  Alice  January      Q1
16 2023-01-17       A   East    682     79   John  January      Q1
17 2023-01-18       B   West    467     70  Marry  January      Q1
18 2023-01-19       C  North    649     58    Bob  January      Q1
19 2023-01-20       D  South    158     94  Alice  January      Q1

In [39]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product      A      B      C      D
Region
East     263.0    NaN    NaN    NaN
North      NaN    NaN  523.0    NaN
South      NaN    NaN    NaN  391.0
West       NaN  467.0    NaN    NaN

In [40]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     386.8    NaN    NaN    NaN  84.4   NaN   NaN   NaN
North      NaN    NaN  515.4    NaN   NaN   NaN  40.4   NaN
South      NaN    NaN    NaN  382.8   NaN   NaN   NaN  67.2
West       NaN  441.8    NaN    NaN   NaN  48.2   NaN   NaN

In [41]:
pd.pivot_table(df,values='Sales',index=['Quarter','Region'],columns='Product',aggfunc='sum')

Product              A       B       C       D
Quarter Region
Q1      East    1934.0     NaN     NaN     NaN
        North      NaN     NaN  2577.0     NaN
        South      NaN     NaN     NaN  1914.0
        West       NaN  2209.0     NaN     NaN

In [42]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [43]:
pd.crosstab(df['Region'],df['Product'],normalize='index')

Product    A    B    C    D
Region
East     1.0  0.0  0.0  0.0
North    0.0  0.0  1.0  0.0
South    0.0  0.0  0.0  1.0
West     0.0  1.0  0.0  0.0

In [45]:
df = pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,20,30,40,50],
    'C':[100,200,300,400,500]
})
df

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [46]:
df["A"]+10

0    11
1    12
2    13
3    14
4    15
Name: A, dtype: int64

In [47]:
def sqr(x):
    return x**2

In [48]:
df["D"]=df["A"].apply(sqr)
df

   A   B    C   D
0  1  10  100   1
1  2  20  200   4
2  3  30  300   9
3  4  40  400  16
4  5  50  500  25

In [49]:
df['E']=df["B"].apply(lambda x:x*2)