In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('titanicv1.csv')
df

,survived,pclass,gender,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [6]:
df.shape

(891, 15)

In [7]:
df.isnull().sum()

survived         0
pclass           0
gender           0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(107)

In [9]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
886     True
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [10]:
df.dtypes

survived         int64
pclass           int64
gender          object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

In [11]:
# df["age"] = df["age"].bfill()
# df["age"] = df["age"].bfill()

In [12]:
#function to load the data(input file name), returns dataframe

def LoadDataset(file):
    d=pd.read_csv(file)
    return d

df_new=LoadDataset('titanicv1 - titanicv1.csv')
print(df_new)

FileNotFoundError: [Errno 2] No such file or directory: 'titanicv1 - titanicv1.csv'

In [19]:
#function to understand dataframe(input dataframe) output is info, stats, datatype, rows & columns
def TheDataframe(d1):
    d1.info()
    d1.describe()
    d1.shape
    
TheDataframe(df_new)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   gender       891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [18]:
#function to check missing values(input df), return no of missing values in each column,
def CheckMissing(d1):
    a=d1.isnull().sum()
    return a
CheckMissing(df_new)

survived         0
pclass           0
gender           0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [20]:
#percentage of missing values in each column
df["age"].isna().mean() * 100

np.float64(19.865319865319865)

In [21]:
df["deck"].isna().mean() * 100

np.float64(77.21661054994388)

In [13]:
from sklearn.impute import SimpleImputer
SI=SimpleImputer(missing_values=np.nan, strategy='mean')
df.iloc[:,3:4]=SI.fit_transform(df.iloc[:,3:4])
df.isnull().sum()

survived         0
pclass           0
gender           0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [14]:
df.drop(columns=['deck'], inplace=True, axis=1)
df.columns

Index(['survived', 'pclass', 'gender', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'embark_town', 'alive',
       'alone'],
      dtype='object')

In [15]:
#Apply Encoding
df_cat=df.select_dtypes(exclude=np.number)
df_cat

     gender embarked   class    who  adult_male  embark_town alive  alone
0      male        S   Third    man        True  Southampton    no  False
1    female        C   First  woman       False    Cherbourg   yes  False
2    female        S   Third  woman       False  Southampton   yes   True
3    female        S   First  woman       False  Southampton   yes  False
4      male        S   Third    man        True  Southampton    no   True
..      ...      ...     ...    ...         ...          ...   ...    ...
886    male        S  Second    man        True  Southampton    no   True
887  female        S   First  woman       False  Southampton   yes   True
888  female        S   Third  woman       False  Southampton    no  False
889    male        C   First    man        True    Cherbourg   yes   True
890    male        Q   Third    man        True   Queenstown    no   True

[891 rows x 8 columns]

In [21]:
# check unique values in each column
for col in df_cat.columns:
    print(col, ':', '\n',df[col].nunique)

gender :
 <bound method IndexOpsMixin.nunique of 0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: gender, Length: 891, dtype: object>
class :
 <bound method IndexOpsMixin.nunique of 0       Third
1       First
2       Third
3       First
4       Third
        ...
886    Second
887     First
888     Third
889     First
890     Third
Name: class, Length: 891, dtype: object>
who :
 <bound method IndexOpsMixin.nunique of 0        man
1      woman
2      woman
3      woman
4        man
       ...
886      man
887    woman
888    woman
889      man
890      man
Name: who, Length: 891, dtype: object>
adult_male :
 <bound method IndexOpsMixin.nunique of 0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888    False
889     True
890     True
Name: adult_male, Length: 891, dtype: bool>
embark_town :
 <bound method IndexOpsMixin.nunique of 0      Southampton
1        Cherbourg
2      Southampton
3      Southampton
4      Southampton
          ...
886    Southampton
887    Southampton
888    Southampton
889      Cherbourg
890     Queenstown
Name: embark_town, Length: 891, dtype: object>
alone :
 <bound method IndexOpsMixin.nunique of 0      False
1      False
2       True
3      False
4       True
       ...
886     True
887     True
888    False
889     True
890     True
Name: alone, Length: 891, dtype: bool>

In [ ]:
#Label Encoding:Gender,adult_male,alone
# drop embarked and alive
#one hot encoding:embark_town, who
#ordinal encoding:class

In [17]:
df_cat.columns

Index(['gender', 'embarked', 'class', 'who', 'adult_male', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [18]:
df_cat.drop(columns=['embarked','alive'], axis=1, inplace=True)
df_cat

     gender   class    who  adult_male  embark_town  alone
0      male   Third    man        True  Southampton  False
1    female   First  woman       False    Cherbourg  False
2    female   Third  woman       False  Southampton   True
3    female   First  woman       False  Southampton  False
4      male   Third    man        True  Southampton   True
..      ...     ...    ...         ...          ...    ...
886    male  Second    man        True  Southampton   True
887  female   First  woman       False  Southampton   True
888  female   Third  woman       False  Southampton  False
889    male   First    man        True    Cherbourg   True
890    male   Third    man        True   Queenstown   True

[891 rows x 6 columns]

In [19]:
df_cat.columns

Index(['gender', 'class', 'who', 'adult_male', 'embark_town', 'alone'], dtype='object')

In [20]:
from sklearn.preprocessing import LabelEncoder
LE=LabelEncoder()
le_column=[0,3,5]
for i in le_column:
    df.iloc[:,i]=LE.fit_transform(df.iloc[:,i])