In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('unclean_data.csv',encoding='latin1')

In [3]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                14 non-null     object
 1   num_critic_for_reviews     14 non-null     int64
 2   duration                   11 non-null     float64
 3   DIRECTOR_facebook_likes    12 non-null     object
 4   actor_3_facebook_likes     14 non-null     int64
 5   ACTOR_1_facebook_likes     14 non-null     int64
 6   gross                      14 non-null     int64
 7   num_voted_users            13 non-null     float64
 8   Cast_Total_facebook_likes  12 non-null     float64
 9   facenumber_in_poster       9 non-null      float64
 10  num_user_for_reviews       14 non-null     int64
 11  budget                     14 non-null     int64
 12  title_year                 14 non-null     int64
 13  ACTOR_2_facebook_likes     13 non-null     float64
 14  imdb_score                 14 non-null     float64
 15  title_year.1               7 non-null      float64
dtypes: float64(7), int64(7), object(2)
memory usage: 1.9+ KB

In [5]:
df.describe()

,num_critic_for_reviews,duration,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
count,14.000000,11.000000,14.000000,14.000000,1.400000e+01,1.300000e+01,12.000000,9.000000,14.000000,1.400000e+01,14.000000,13.000000,14.000000,7.000000
mean,506.142857,150.727273,5866.142857,18206.428571,3.335836e+08,4.621578e+05,44773.583333,2.111111,1620.071429,2.462643e+08,2010.500000,8455.846154,7.171429,2011.142857
std,169.069789,21.679903,8289.592695,13905.214361,1.720674e+08,2.687059e+05,37290.813335,1.269296,866.672102,2.426823e+07,3.632122,8541.019541,0.673028,3.976119
min,302.000000,106.000000,161.000000,451.000000,7.305868e+07,2.122040e+05,1873.000000,1.000000,387.000000,2.000000e+08,2006.000000,393.000000,6.100000,2007.000000
25%,379.250000,141.000000,611.250000,3500.000000,2.002574e+08,2.948100e+05,9983.500000,1.000000,1024.750000,2.390000e+08,2007.250000,632.000000,6.725000,2008.000000
50%,448.000000,151.000000,1000.000000,21000.000000,3.198266e+08,3.830560e+05,47202.500000,2.000000,1240.500000,2.500000e+08,2009.500000,5000.000000,7.200000,2009.000000
75%,635.000000,162.500000,8500.000000,26000.000000,4.418561e+08,4.712200e+05,67064.750000,3.000000,2250.750000,2.560000e+08,2014.250000,11000.000000,7.500000,2015.000000
max,813.000000,183.000000,23000.000000,40000.000000,7.605058e+08,1.144337e+06,106759.000000,4.000000,3054.000000,3.000000e+08,2016.000000,23000.000000,8.500000,2016.000000

In [6]:
df.columns

Index(['movie_title', 'num_critic_for_reviews', 'duration',
       'DIRECTOR_facebook_likes', 'actor_3_facebook_likes',
       'ACTOR_1_facebook_likes', 'gross', 'num_voted_users',
       'Cast_Total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'ACTOR_2_facebook_likes', 'imdb_score', 'title_year.1'],
      dtype='object')

In [7]:
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     3
DIRECTOR_facebook_likes      2
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              1
Cast_Total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [8]:
df.isnull().any()

movie_title                  False
num_critic_for_reviews       False
duration                      True
DIRECTOR_facebook_likes       True
actor_3_facebook_likes       False
ACTOR_1_facebook_likes       False
gross                        False
num_voted_users               True
Cast_Total_facebook_likes     True
facenumber_in_poster          True
num_user_for_reviews         False
budget                       False
title_year                   False
ACTOR_2_facebook_likes        True
imdb_score                   False
title_year.1                  True
dtype: bool

In [9]:
df.isnull().sum().sum()

np.int64(21)

In [10]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar?ÿ,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End?ÿ,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre?ÿ,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises?ÿ,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter?ÿ,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [13]:
df["movie_title"]=(df["movie_title"].str.replace("?ÿ","",regex=False).str.strip())

In [14]:
df.head()

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar,723,178.0,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,NaN,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.0,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,NaN,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.0,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN

In [16]:
df['duration']=df['duration'].fillna(df['duration'].mean())

In [17]:
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     0
DIRECTOR_facebook_likes      2
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              1
Cast_Total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [18]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [19]:
df.duplicated('movie_title')

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9     False
10    False
11    False
12    False
13    False
dtype: bool

In [20]:
df.head(10)

,movie_title,num_critic_for_reviews,duration,DIRECTOR_facebook_likes,actor_3_facebook_likes,ACTOR_1_facebook_likes,gross,num_voted_users,Cast_Total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,ACTOR_2_facebook_likes,imdb_score,title_year.1
0,Avatar,723,178.000000,10,855,1000,760505847,886204.0,4834.0,NaN,3054,237000000,2009,936.0,7.9,2009.0
1,Pirates of the Caribbean: At World's End,302,150.727273,563,1000,40000,309404152,471220.0,48350.0,NaN,1238,300000000,2007,5000.0,7.1,NaN
2,Spectre,602,148.000000,20,161,11000,200074175,275868.0,11700.0,1.0,994,245000000,2015,393.0,6.8,2015.0
3,The Dark Knight Rises,813,150.727273,22000,23000,27000,448130642,1144337.0,106759.0,NaN,2701,250000000,2012,23000.0,8.5,NaN
4,John Carter,462,132.000000,"""475""",530,640,73058679,212204.0,1873.0,1.0,738,263700000,2012,632.0,6.6,NaN
5,Spider-Man 3,392,156.000000,23,4000,24000,336530303,383056.0,46055.0,NaN,1902,258000000,2007,11000.0,6.2,2007.0
6,Tangled,324,150.727273,15,284,799,200807262,294810.0,NaN,1.0,387,260000000,2010,553.0,7.8,NaN
7,Avengers: Age of Ultron,635,141.000000,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,NaN
8,Avengers: Age of Ultron,635,141.000000,10,19000,26000,458991599,462669.0,92000.0,4.0,1117,250000000,2015,21000.0,7.5,2015.0
9,Harry Potter and the Half-Blood Prince,375,153.000000,282,10000,25000,301956980,321795.0,58753.0,3.0,973,250000000,2009,11000.0,7.5,NaN

In [21]:
df.shape

(14, 16)

In [22]:
df = df.drop_duplicates('movie_title')

In [23]:
df.shape

(13, 16)

In [24]:
df.isnull().sum()

movie_title                  0
num_critic_for_reviews       0
duration                     0
DIRECTOR_facebook_likes      2
actor_3_facebook_likes       0
ACTOR_1_facebook_likes       0
gross                        0
num_voted_users              1
Cast_Total_facebook_likes    2
facenumber_in_poster         5
num_user_for_reviews         0
budget                       0
title_year                   0
ACTOR_2_facebook_likes       1
imdb_score                   0
title_year.1                 7
dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 13
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                13 non-null     object
 1   num_critic_for_reviews     13 non-null     int64
 2   duration                   13 non-null     float64
 3   DIRECTOR_facebook_likes    11 non-null     object
 4   actor_3_facebook_likes     13 non-null     int64
 5   ACTOR_1_facebook_likes     13 non-null     int64
 6   gross                      13 non-null     int64
 7   num_voted_users            12 non-null     float64
 8   Cast_Total_facebook_likes  11 non-null     float64
 9   facenumber_in_poster       8 non-null      float64
 10  num_user_for_reviews       13 non-null     int64
 11  budget                     13 non-null     int64
 12  title_year                 13 non-null     int64
 13  ACTOR_2_facebook_likes     12 non-null     float64
 14  imdb_score                 13 non-null     float64
 15  title_year.1               6 non-null      float64
dtypes: float64(7), int64(7), object(2)
memory usage: 1.7+ KB

In [26]:
df.drop('title_year.1',axis=1,inplace=True)

In [30]:
df.isnull().sum()

movie_title                   0
num_critic_for_reviews        0
duration                      0
DIRECTOR_facebook_likes       2
actor_3_facebook_likes        0
ACTOR_1_facebook_likes        0
gross                         0
num_voted_users               1
Cast_Total_facebook_likes     2
facenumber_in_poster         13
num_user_for_reviews          0
budget                        0
title_year                    0
ACTOR_2_facebook_likes        1
imdb_score                    0
dtype: int64

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 13
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                13 non-null     object
 1   num_critic_for_reviews     13 non-null     int64
 2   duration                   13 non-null     float64
 3   DIRECTOR_facebook_likes    11 non-null     object
 4   actor_3_facebook_likes     13 non-null     int64
 5   ACTOR_1_facebook_likes     13 non-null     int64
 6   gross                      13 non-null     int64
 7   num_voted_users            12 non-null     float64
 8   Cast_Total_facebook_likes  11 non-null     float64
 9   facenumber_in_poster       0 non-null      object
 10  num_user_for_reviews       13 non-null     int64
 11  budget                     13 non-null     int64
 12  title_year                 13 non-null     int64
 13  ACTOR_2_facebook_likes     12 non-null     float64
 14  imdb_score                 13 non-null     float64
dtypes: float64(5), int64(7), object(3)
memory usage: 1.6+ KB

In [32]:
df["DIRECTOR_facebook_likes"]=pd.to_numeric(df["DIRECTOR_facebook_likes"],errors='coerce')

In [35]:
median_cols=[
    "DIRECTOR_facebook_likes",
    "num_voted_users",
    "Cast_Total_facebook_likes",
    "ACTOR_2_facebook_likes"
]
# for col in median_cols:
#     df[col].fillna(df[col].median(),inplace=True)

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13 entries, 0 to 13
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   movie_title                13 non-null     object
 1   num_critic_for_reviews     13 non-null     int64
 2   duration                   13 non-null     float64
 3   DIRECTOR_facebook_likes    10 non-null     float64
 4   actor_3_facebook_likes     13 non-null     int64
 5   ACTOR_1_facebook_likes     13 non-null     int64
 6   gross                      13 non-null     int64
 7   num_voted_users            12 non-null     float64
 8   Cast_Total_facebook_likes  11 non-null     float64
 9   facenumber_in_poster       0 non-null      object
 10  num_user_for_reviews       13 non-null     int64
 11  budget                     13 non-null     int64
 12  title_year                 13 non-null     int64
 13  ACTOR_2_facebook_likes     12 non-null     float64
 14  imdb_score                 13 non-null     float64
dtypes: float64(6), int64(7), object(2)
memory usage: 1.6+ KB

In [ ]:
df