In [1]:
import pandas as pd
import numpy as np

In [43]:
data = pd.read_csv('data_clean.csv')

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 158 entries, 0 to 157
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  158 non-null    int64
 1   Ozone       120 non-null    float64
 2   Solar.R     151 non-null    float64
 3   Wind        158 non-null    float64
 4   Temp C      158 non-null    object
 5   Month       158 non-null    object
 6   Day         158 non-null    int64
 7   Year        158 non-null    int64
 8   Temp        158 non-null    int64
 9   Weather     155 non-null    object
dtypes: float64(3), int64(4), object(3)
memory usage: 12.5+ KB

In [45]:
data.isnull().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [5]:
data.describe()

,Unnamed: 0,Ozone,Solar.R,Wind,Day,Year,Temp
count,158.000000,120.000000,151.000000,158.000000,158.000000,158.0,158.000000
mean,79.500000,41.583333,185.403974,9.957595,16.006329,2010.0,77.727848
std,45.754781,32.620709,88.723103,3.511261,8.997166,0.0,9.377877
min,1.000000,1.000000,7.000000,1.700000,1.000000,2010.0,56.000000
25%,40.250000,18.000000,119.000000,7.400000,8.000000,2010.0,72.000000
50%,79.500000,30.500000,197.000000,9.700000,16.000000,2010.0,78.500000
75%,118.750000,61.500000,257.000000,11.875000,24.000000,2010.0,84.000000
max,158.000000,168.000000,334.000000,20.700000,31.000000,2010.0,97.000000

In [46]:
data['Ozone']  = data['Ozone'].fillna(data['Ozone'].mean())

In [7]:
data.head()

   Unnamed: 0      Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1  41.000000    190.0   7.4     67     5    1  2010    67       S
1           2  36.000000    118.0   8.0     72     5    2  2010    72       C
2           3  12.000000    149.0  12.6     74     5    3  2010    74      PS
3           4  18.000000    313.0  11.5     62     5    4  2010    62       S
4           5  41.583333      NaN  14.3     56     5    5  2010    56       S

In [8]:
data.head(10)

   Unnamed: 0      Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1  41.000000    190.0   7.4     67     5    1  2010    67       S
1           2  36.000000    118.0   8.0     72     5    2  2010    72       C
2           3  12.000000    149.0  12.6     74     5    3  2010    74      PS
3           4  18.000000    313.0  11.5     62     5    4  2010    62       S
4           5  41.583333      NaN  14.3     56     5    5  2010    56       S
5           6  28.000000      NaN  14.9     66     5    6  2010    66       C
6           7  23.000000    299.0   8.6     65     5    7  2010    65      PS
7           8  19.000000     99.0  13.8     59     5    8  2010    59       C
8           9   8.000000     19.0  20.1     61     5    9  2010    61      PS
9          10  41.583333    194.0   8.6     69     5   10  2010    69       S

In [9]:
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       7
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       3
dtype: int64

In [20]:
data.head()

   Unnamed: 0      Ozone     Solar.R  Wind Temp C Month  Day  Year Weather
0           1  41.000000  190.000000   7.4     67     5    1  2010       S
1           2  36.000000  118.000000   8.0     72     5    2  2010       C
2           3  12.000000  149.000000  12.6     74     5    3  2010      PS
3           4  18.000000  313.000000  11.5     62     5    4  2010       S
4           5  41.583333  185.403974  14.3     56     5    5  2010       S

In [47]:
data['Solar.R']  = data['Solar.R'].fillna(data['Solar.R'].mean())

In [12]:
data.head()

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
0,1,41.000000,190.000000,7.4,67,5,1,2010,67,S
1,2,36.000000,118.000000,8.0,72,5,2,2010,72,C
2,3,12.000000,149.000000,12.6,74,5,3,2010,74,PS
3,4,18.000000,313.000000,11.5,62,5,4,2010,62,S
4,5,41.583333,185.403974,14.3,56,5,5,2010,56,S

In [13]:
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       0
Wind          0
Temp C        0
Month         0
Day           0
Year          0
Temp          0
Weather       3
dtype: int64

In [14]:
data.head()

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
0,1,41.000000,190.000000,7.4,67,5,1,2010,67,S
1,2,36.000000,118.000000,8.0,72,5,2,2010,72,C
2,3,12.000000,149.000000,12.6,74,5,3,2010,74,PS
3,4,18.000000,313.000000,11.5,62,5,4,2010,62,S
4,5,41.583333,185.403974,14.3,56,5,5,2010,56,S

In [48]:
data = data.drop('Temp C', axis=1)

In [25]:
data.head()

   Unnamed: 0      Ozone     Solar.R  Wind Month  Day  Year  Temp Weather
0           1  41.000000  190.000000   7.4     5    1  2010    67       S
1           2  36.000000  118.000000   8.0     5    2  2010    72       C
2           3  12.000000  149.000000  12.6     5    3  2010    74      PS
3           4  18.000000  313.000000  11.5     5    4  2010    62       S
4           5  41.583333  185.403974  14.3     5    5  2010    56       S

In [26]:
data.isnull().sum().sum()

np.int64(3)

In [49]:
data['Weather'] = data['Weather'].ffill()

In [31]:
data.isnull().sum()

Unnamed: 0    0
Ozone         0
Solar.R       0
Wind          0
Month         0
Day           0
Year          0
Temp          0
Weather       0
dtype: int64

In [51]:
data['Month'] = data['Month'].replace('May', 5).astype(int)

data['date'] = pd.to_datetime({
    'year': data['Year'],
    'month': data['Month'],
    'day': data['Day']
})

In [52]:
data.head()

,Unnamed: 0,Ozone,Solar.R,Wind,Month,Day,Year,Temp,Weather,date
0,1,41.000000,190.000000,7.4,5,1,2010,67,S,2010-05-01
1,2,36.000000,118.000000,8.0,5,2,2010,72,C,2010-05-02
2,3,12.000000,149.000000,12.6,5,3,2010,74,PS,2010-05-03
3,4,18.000000,313.000000,11.5,5,4,2010,62,S,2010-05-04
4,5,41.583333,185.403974,14.3,5,5,2010,56,S,2010-05-05

In [53]:
data = data.drop(['Day', 'Month', 'Year'], axis=1)

In [39]:
data.head()

   Unnamed: 0      Ozone     Solar.R  Wind  Temp Weather       date
0           1  41.000000  190.000000   7.4    67       S 2010-01-05
1           2  36.000000  118.000000   8.0    72       C 2010-02-05
2           3  12.000000  149.000000  12.6    74      PS 2010-03-05
3           4  18.000000  313.000000  11.5    62       S 2010-04-05
4           5  41.583333  185.403974  14.3    56       S 2010-05-05

In [54]:
hottest_days = data.sort_values(by='Temp',ascending=False).head(5)
print(hottest_days)

     Unnamed: 0       Ozone  Solar.R  Wind  Temp Weather       date
119         120   76.000000    203.0   9.7    97       S 2010-08-28
121         122   84.000000    237.0   6.3    96       S 2010-08-30
120         121  118.000000    225.0   2.3    94       S 2010-08-29
122         123   85.000000    188.0   6.3    94       C 2010-08-31
41           42   41.583333    259.0  10.9    93       C 2010-06-11

In [42]:
avg_ozone = data.groupby('Weather')['Ozone'].mean().sort_values(ascending=False)
print(avg_ozone)

Weather
C     45.180000
PS    42.110544
S     38.097458
Name: Ozone, dtype: float64

In [56]:
temp_avg = data[
    (data['Temp'] > data['Temp'].mean()) &
    (data['Ozone'] < data['Ozone'].mean())
]

print(temp_avg)

     Unnamed: 0      Ozone     Solar.R  Wind  Temp Weather       date
31           32  41.583333  286.000000   8.6    78       S 2010-06-01
34           35  41.583333  186.000000   9.2    84       C 2010-06-04
35           36  41.583333  220.000000   8.6    85      PS 2010-06-05
36           37  41.583333  264.000000  14.3    79       C 2010-06-06
37           38  29.000000  127.000000   9.7    82      PS 2010-06-07
38           39  41.583333  273.000000   6.9    87       S 2010-06-08
40           41  39.000000  323.000000  11.5    87       S 2010-06-10
41           42  41.583333  259.000000  10.9    93       C 2010-06-11
42           43  41.583333  250.000000   9.2    92      PS 2010-06-12
43           44  23.000000  148.000000   8.0    82       S 2010-06-13
44           45  41.583333  332.000000  13.8    80       S 2010-06-14
45           46  41.583333  322.000000  11.5    79       C 2010-06-15
56           57  41.583333  127.000000   8.0    78      PS 2010-06-26
58           59  41.583333   98.000000  11.5    80      PS 2010-06-28
60           61  41.583333  138.000000   8.0    83       S 2010-06-30
63           64  32.000000  236.000000   9.2    81      PS 2010-07-03
64           65  41.583333  101.000000  10.9    84       S 2010-07-04
66           67  40.000000  314.000000  10.9    83       C 2010-07-06
71           72  41.583333  139.000000   8.6    82       S 2010-07-11
73           74  27.000000  175.000000  14.9    81       S 2010-07-13
74           75  41.583333  291.000000  14.9    91       C 2010-07-14
75           76   7.000000   48.000000  14.3    80      PS 2010-07-15
77           78  35.000000  274.000000  10.3    82       S 2010-07-17
82           83  41.583333  258.000000   9.7    81       S 2010-07-22
83           84  41.583333  295.000000  11.5    82       C 2010-07-23
86           87  20.000000   81.000000   8.6    82       C 2010-07-26
92           93  39.000000   83.000000   6.9    81      PS 2010-08-01
93           94   9.000000   24.000000  13.8    81      PS 2010-08-02
94           95  16.000000   77.000000   7.4    82      PS 2010-08-03
96           97  35.000000  185.403974   7.4    85       S 2010-08-05
101         102  41.583333  222.000000   8.6    92      PS 2010-08-10
102         103  41.583333  137.000000  11.5    86       S 2010-08-11
104         105  28.000000  273.000000  11.5    82       S 2010-08-13
106         107  41.583333   64.000000  11.5    79       C 2010-08-15
110         111  31.000000  244.000000  10.9    78      PS 2010-08-19
118         119  41.583333  153.000000   5.7    88       S 2010-08-27
128         129  32.000000   92.000000  15.5    84       S 2010-09-06
129         130  20.000000  252.000000  10.9    80       S 2010-09-07
130         131  23.000000  220.000000  10.3    78       C 2010-09-08
142         143  16.000000  201.000000   8.0    82      PS 2010-09-20
145         146  36.000000  139.000000  10.3    81       S 2010-09-23

In [58]:
data['Heat Level'] = np.where(data['Temp'] > 80, 'High', 'Low')

In [59]:
data.head()

   Unnamed: 0      Ozone     Solar.R  Wind  Temp Weather       date Heat Level
0           1  41.000000  190.000000   7.4    67       S 2010-05-01        Low
1           2  36.000000  118.000000   8.0    72       C 2010-05-02        Low
2           3  12.000000  149.000000  12.6    74      PS 2010-05-03        Low
3           4  18.000000  313.000000  11.5    62       S 2010-05-04        Low
4           5  41.583333  185.403974  14.3    56       S 2010-05-05        Low

In [63]:
avg_solar = data.groupby(data['date'].dt.month_name())['Solar.R'].mean()

print(avg_solar)
print("Month with maximum average Solar Radiation:", avg_solar.idxmax())
print("Average Solar Radiation:", avg_solar.max())

date
August       173.168126
July         216.483871
June         190.166667
May          182.081747
September    167.147059
Name: Solar.R, dtype: float64
Month with maximum average Solar Radiation: July
Average Solar Radiation: 216.48387096774192