In [2]:
import pandas as pd
df = pd.read_csv('people_data.csv')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
1,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
5,ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
6,marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
7,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
8,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [7]:
print(df.dtypes)
print(type(df))

First Name       object
Last Name        object
Sex              object
Email            object
Date of birth    object
Job Title        object
dtype: object
<class 'pandas.core.frame.DataFrame'>

In [8]:
df = pd.read_csv('people_data.csv',index_col='First Name')
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [9]:
df = pd.read_csv('people_data.csv',na_values=['n/a','unknown'])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
1,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
5,ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
6,marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
7,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
8,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [10]:
df = pd.read_csv('people_data.csv',nrows =3, usecols=['First Name','Sex'])
df

  First Name     Sex
0     Shelby    Male
1    Phillip  Female
2   Kristine    Male

In [11]:
df = pd.read_csv('people_data.csv',skiprows=[1,2])
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
1,Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
2,Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
3,ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
4,marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
5,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
6,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [12]:
df = pd.read_csv('people_data.csv',skiprows=[0,2])
df

,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
0,Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
1,Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
2,Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
3,ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
4,marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
5,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
6,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [13]:
df.isna()

   Shelby  Terrell   Male  elijah57@example.net  26-10-1945  Games developer
0   False    False  False                 False       False            False
1   False    False  False                 False       False            False
2   False    False  False                 False       False            False
3   False    False  False                 False       False            False
4   False    False  False                 False       False            False
5   False    False  False                 False       False            False
6   False    False  False                 False       False            False

In [15]:
df.isna().sum()

Shelby                  0
Terrell                 0
Male                    0
elijah57@example.net    0
26-10-1945              0
Games developer         0
dtype: int64

In [16]:
df = pd.read_csv('people_data.csv')
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
1,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,02-07-1992,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,03-08-2017,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,01-12-1938,Veterinary surgeon
5,ella,mustin,Female,ella23@gmail.com,02-03-1996,Engineer
6,marie,john,Female,johnmary@gmail.com,09-10-1998,Telecaller
7,Shelby,Terrell,Male,elijah57@example.net,26-10-1945,Games developer
8,Phillip,Summers,Female,bethany14@example.com,24-03-1910,Phytotherapist

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     9 non-null      object
 1   Last Name      9 non-null      object
 2   Sex            9 non-null      object
 3   Email          9 non-null      object
 4   Date of birth  9 non-null      object
 5   Job Title      9 non-null      object
dtypes: object(6)
memory usage: 564.0+ bytes

In [ ]:
what is the distribution and breakdown of the 'Sex' column?

In [18]:
gender_counts = df['Sex'].value_counts()
gender_percentages=df['Sex'].value_counts(normalize=True)*100

In [19]:
gender_counts

Sex
Male      5
Female    4
Name: count, dtype: int64

In [20]:
gender_percentages

Sex
Male      55.555556
Female    44.444444
Name: proportion, dtype: float64

In [21]:
top_jobs = df['Job Title'].value_counts().head(5)

In [23]:
df['Date of birth'] = pd.to_datetime(df['Date of birth'])
current_year = 2026
df['Age'] = current_year-df['Date of birth'].dt.year
print(df['Age'].describe())

count      9.000000
mean      64.777778
std       40.208139
min        9.000000
25%       30.000000
50%       81.000000
75%       88.000000
max      116.000000
Name: Age, dtype: float64

C:\Users\Rudra Pratap Singh\AppData\Local\Temp\ipykernel_18488\804177735.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['Date of birth'] = pd.to_datetime(df['Date of birth'])

In [25]:
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title,Date of Birth,Age
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer,1945-10-26,81
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist,1910-03-24,116
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath,1992-07-02,34
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher,2017-08-03,9
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon,1938-12-01,88
5,ella,mustin,Female,ella23@gmail.com,1996-03-02,Engineer,1996-03-02,30
6,marie,john,Female,johnmary@gmail.com,1998-10-09,Telecaller,1998-10-09,28
7,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer,1945-10-26,81
8,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist,1910-03-24,116

In [26]:
df['Date of birth'] = pd.to_datetime(df['Date of birth'])
result = df[df["Date of birth"].dt.year>1990]
print(result)

  First Name Last Name     Sex                      Email Date of birth  \
2   Kristine    Travis    Male      bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male  kaitlinkaiser@example.com    2017-08-03
5       ella   mustin   Female           ella23@gmail.com    1996-03-02
6      marie      john  Female         johnmary@gmail.com    1998-10-09

           Job Title Date of Birth  Age
2          Homeopath    1992-07-02   34
3  Market researcher    2017-08-03    9
5           Engineer    1996-03-02   30
6         Telecaller    1998-10-09   28

In [27]:
from datetime import datetime
current_year = datetime.now().year
df["Age"] = current_year- df["Date of birth"].dt.year
print(df)

  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01
5       ella   mustin   Female            ella23@gmail.com    1996-03-02
6      marie      john  Female          johnmary@gmail.com    1998-10-09
7     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
8    Phillip   Summers  Female       bethany14@example.com    1910-03-24

            Job Title Date of Birth  Age
0     Games developer    1945-10-26   81
1      Phytotherapist    1910-03-24  116
2           Homeopath    1992-07-02   34
3   Market researcher    2017-08-03    9
4  Veterinary surgeon    1938-12-01   88
5            Engineer    1996-03-02   30
6          Telecaller    1998-10-09   28
7     Games developer    1945-10-26   81
8      Phytotherapist    1910-03-24  116

In [28]:
oldest  = df.loc[df["Age"].idxmax()]
print(oldest)

First Name                     Phillip
Last Name                      Summers
Sex                             Female
Email            bethany14@example.com
Date of birth      1910-03-24 00:00:00
Job Title               Phytotherapist
Date of Birth      1910-03-24 00:00:00
Age                                116
Name: 1, dtype: object

In [29]:
df["Domain"] = df["Email"].str.split("@").str[1]
print(df[["Email","Domain"]])

                        Email       Domain
0        elijah57@example.net  example.net
1       bethany14@example.com  example.com
2       bthompson@example.com  example.com
3   kaitlinkaiser@example.com  example.com
4  buchananmanuel@example.net  example.net
5            ella23@gmail.com    gmail.com
6          johnmary@gmail.com    gmail.com
7        elijah57@example.net  example.net
8       bethany14@example.com  example.com

In [ ]:
duplicate_emails = df.duplicated(subset=['Email']).sum()
print(f"Number of duplicate email entries:{duplicate_emails}")

if duplicate_emails>0:
    duplicated(subset=['Email'],keep = False)]