In [1]:
import pandas as pd 
import numpy as np

In [2]:
sales_data = pd.read_csv('sales_data_sample.csv',encoding="latin-1")
sales_data.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [3]:
sales_data.shape
sales_data.info()
sales_data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [4]:
sales_data.duplicated().sum()

np.int64(0)

In [5]:
sales_data.isna().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [6]:
sales_data.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [7]:
for col in sales_data.columns:
    print(f'Number of {col} unique values:{sales_data[col].nunique()}')

Number of ORDERNUMBER unique values:307
Number of QUANTITYORDERED unique values:58
Number of PRICEEACH unique values:1016
Number of ORDERLINENUMBER unique values:18
Number of SALES unique values:2763
Number of ORDERDATE unique values:252
Number of STATUS unique values:6
Number of QTR_ID unique values:4
Number of MONTH_ID unique values:12
Number of YEAR_ID unique values:3
Number of PRODUCTLINE unique values:7
Number of MSRP unique values:80
Number of PRODUCTCODE unique values:109
Number of CUSTOMERNAME unique values:92
Number of PHONE unique values:91
Number of ADDRESSLINE1 unique values:92
Number of ADDRESSLINE2 unique values:9
Number of CITY unique values:73
Number of STATE unique values:16
Number of POSTALCODE unique values:73
Number of COUNTRY unique values:19
Number of TERRITORY unique values:3
Number of CONTACTLASTNAME unique values:77
Number of CONTACTFIRSTNAME unique values:72
Number of DEALSIZE unique values:3

In [8]:
sales_data['ORDERDATE']=pd.to_datetime(sales_data['ORDERDATE'])
sales_data.sort_values(by = ['ORDERDATE'],inplace = True)
sales_data.set_index('ORDERDATE',inplace = True)

In [9]:
sales_data.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [10]:
sales_data.head(30)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
ORDERDATE,,,,,,,,,,,,,,,,,,,,,
2003-01-06,10100,30,100.00,3,5151.00,Shipped,1,1,2003,Vintage Cars,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
2003-01-06,10100,50,67.80,2,3390.00,Shipped,1,1,2003,Vintage Cars,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Medium
2003-01-06,10100,22,86.51,4,1903.22,Shipped,1,1,2003,Vintage Cars,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
2003-01-06,10100,49,34.47,1,1689.03,Shipped,1,1,2003,Vintage Cars,...,2304 Long Airport Avenue,NaN,Nashua,NH,62005,USA,NaN,Young,Valarie,Small
2003-01-09,10101,45,31.20,3,1404.00,Shipped,1,1,2003,Vintage Cars,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Small
2003-01-09,10101,46,53.76,2,2472.96,Shipped,1,1,2003,Vintage Cars,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Small
2003-01-09,10101,25,100.00,4,3782.00,Shipped,1,1,2003,Vintage Cars,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Medium
2003-01-09,10101,26,100.00,1,3773.38,Shipped,1,1,2003,Vintage Cars,...,Lyonerstr. 34,NaN,Frankfurt,NaN,60528,Germany,EMEA,Keitel,Roland,Medium
2003-01-10,10102,41,50.14,1,2055.74,Shipped,1,1,2003,Vintage Cars,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Small
2003-01-10,10102,39,100.00,2,4808.31,Shipped,1,1,2003,Vintage Cars,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,NaN,Frick,Michael,Medium
2003-01-29,10103,36,100.00,5,4228.20,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,35,100.00,10,3920.00,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,22,54.09,2,1189.98,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,41,47.29,9,1938.89,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,36,100.00,1,3680.28,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,26,100.00,11,5404.62,Shipped,1,1,2003,Classic Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,46,100.00,16,4791.82,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,35,57.46,14,2011.10,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,25,100.00,13,2539.50,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,45,75.63,7,3403.35,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,27,100.00,8,3394.98,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,31,100.00,3,3224.31,Shipped,1,1,2003,Trucks and Buses,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,42,100.00,4,5398.26,Shipped,1,1,2003,Classic Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-29,10103,27,83.07,12,2242.89,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,25,100.00,15,2873.00,Shipped,1,1,2003,Vintage Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Small
2003-01-29,10103,42,100.00,6,4460.82,Shipped,1,1,2003,Classic Cars,...,Erling Skakkes gate 78,NaN,Stavern,NaN,4110,Norway,EMEA,Bergulfsen,Jonas,Medium
2003-01-31,10104,26,100.00,5,2921.62,Shipped,1,1,2003,Classic Cars,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2003-01-31,10104,49,65.87,4,3227.63,Shipped,1,1,2003,Trains,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2003-01-31,10104,24,100.00,8,3457.92,Shipped,1,1,2003,Classic Cars,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2003-01-31,10104,35,47.62,11,1666.70,Shipped,1,1,2003,Trucks and Buses,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small

In [11]:
sales_data.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE',
       'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1',
       'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY',
       'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE'],
      dtype='object')

In [12]:
sales_data['STATE'].unique()

array(['NH', nan, 'NY', 'PA', 'CA', 'Victoria', 'NV', 'MA', 'CT', 'NSW',
       'Queensland', 'Quebec', 'BC', 'Osaka', 'Isle of Wight', 'NJ',
       'Tokyo'], dtype=object)

In [13]:
sales_data.drop(["STATE"],axis=1,inplace=True)

In [ ]:
sales_data.drop(["TERRITORY"],axis=1,inplace=True)

In [16]:
sales_data.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE',
       'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1',
       'ADDRESSLINE2', 'CITY', 'POSTALCODE', 'COUNTRY', 'CONTACTLASTNAME',
       'CONTACTFIRSTNAME', 'DEALSIZE'],
      dtype='object')

In [17]:
sales_data.isnull().sum()

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
POSTALCODE            76
COUNTRY                0
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [20]:
sales_data["ADDRESS"]=sales_data['ADDRESSLINE1']+" "+sales_data["ADDRESSLINE2"].fillna("unknown")

In [21]:
sales_data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,PHONE,ADDRESSLINE1,ADDRESSLINE2,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ADDRESS
ORDERDATE,,,,,,,,,,,,,,,,,,,,,
2003-01-06,10100,30,100.00,3,5151.00,Shipped,1,1,2003,Vintage Cars,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,50,67.80,2,3390.00,Shipped,1,1,2003,Vintage Cars,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,22,86.51,4,1903.22,Shipped,1,1,2003,Vintage Cars,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-06,10100,49,34.47,1,1689.03,Shipped,1,1,2003,Vintage Cars,...,6035558647,2304 Long Airport Avenue,NaN,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-09,10101,45,31.20,3,1404.00,Shipped,1,1,2003,Vintage Cars,...,+49 69 66 90 2555,Lyonerstr. 34,NaN,Frankfurt,60528,Germany,Keitel,Roland,Small,Lyonerstr. 34 unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-05-31,10425,18,100.00,2,1895.94,In Process,2,5,2005,Trucks and Buses,...,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Small,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,33,100.00,4,4692.60,In Process,2,5,2005,Trucks and Buses,...,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,38,100.00,12,5894.94,In Process,2,5,2005,Classic Cars,...,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10424,44,61.41,2,2702.04,In Process,2,5,2005,Trucks and Buses,...,(91) 555 94 44,"C/ Moralzarzal, 86",NaN,Madrid,28034,Spain,Freyre,Diego,Small,"C/ Moralzarzal, 86 unknown"
2005-05-31,10425,38,99.41,7,3777.58,In Process,2,5,2005,Trucks and Buses,...,40.67.8555,"67, rue des Cinquante Otages",NaN,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"

In [22]:
sales_data.drop(["ADDRESSLINE1","ADDRESSLINE2"],axis=1,inplace=True)

In [23]:
sales_data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,PRODUCTCODE,CUSTOMERNAME,PHONE,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ADDRESS
ORDERDATE,,,,,,,,,,,,,,,,,,,,,
2003-01-06,10100,30,100.00,3,5151.00,Shipped,1,1,2003,Vintage Cars,...,S18_1749,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,50,67.80,2,3390.00,Shipped,1,1,2003,Vintage Cars,...,S18_2248,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,22,86.51,4,1903.22,Shipped,1,1,2003,Vintage Cars,...,S18_4409,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-06,10100,49,34.47,1,1689.03,Shipped,1,1,2003,Vintage Cars,...,S24_3969,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-09,10101,45,31.20,3,1404.00,Shipped,1,1,2003,Vintage Cars,...,S24_1937,"Blauer See Auto, Co.",+49 69 66 90 2555,Frankfurt,60528,Germany,Keitel,Roland,Small,Lyonerstr. 34 unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-05-31,10425,18,100.00,2,1895.94,In Process,2,5,2005,Trucks and Buses,...,S50_1392,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Small,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,33,100.00,4,4692.60,In Process,2,5,2005,Trucks and Buses,...,S12_4473,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,38,100.00,12,5894.94,In Process,2,5,2005,Classic Cars,...,S10_4962,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10424,44,61.41,2,2702.04,In Process,2,5,2005,Trucks and Buses,...,S32_3522,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Small,"C/ Moralzarzal, 86 unknown"
2005-05-31,10425,38,99.41,7,3777.58,In Process,2,5,2005,Trucks and Buses,...,S18_2319,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"

In [24]:
sales_data.columns

Index(['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER',
       'SALES', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE',
       'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'CITY', 'POSTALCODE',
       'COUNTRY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE',
       'ADDRESS'],
      dtype='object')

In [25]:
sales_data.isnull().sum()

ORDERNUMBER          0
QUANTITYORDERED      0
PRICEEACH            0
ORDERLINENUMBER      0
SALES                0
STATUS               0
QTR_ID               0
MONTH_ID             0
YEAR_ID              0
PRODUCTLINE          0
MSRP                 0
PRODUCTCODE          0
CUSTOMERNAME         0
PHONE                0
CITY                 0
POSTALCODE          76
COUNTRY              0
CONTACTLASTNAME      0
CONTACTFIRSTNAME     0
DEALSIZE             0
ADDRESS              0
dtype: int64

In [26]:
sales_data['POSTALCODE']

ORDERDATE
2003-01-06    62005
2003-01-06    62005
2003-01-06    62005
2003-01-06    62005
2003-01-09    60528
              ...
2005-05-31    44000
2005-05-31    44000
2005-05-31    44000
2005-05-31    28034
2005-05-31    44000
Name: POSTALCODE, Length: 2823, dtype: object

In [28]:
sales_data["POSTALCODE"].fillna("unknown",inplace=True)

In [29]:
sales_data.isnull().sum()

ORDERNUMBER         0
QUANTITYORDERED     0
PRICEEACH           0
ORDERLINENUMBER     0
SALES               0
STATUS              0
QTR_ID              0
MONTH_ID            0
YEAR_ID             0
PRODUCTLINE         0
MSRP                0
PRODUCTCODE         0
CUSTOMERNAME        0
PHONE               0
CITY                0
POSTALCODE          0
COUNTRY             0
CONTACTLASTNAME     0
CONTACTFIRSTNAME    0
DEALSIZE            0
ADDRESS             0
dtype: int64

In [30]:
sales_data

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,PRODUCTCODE,CUSTOMERNAME,PHONE,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ADDRESS
ORDERDATE,,,,,,,,,,,,,,,,,,,,,
2003-01-06,10100,30,100.00,3,5151.00,Shipped,1,1,2003,Vintage Cars,...,S18_1749,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,50,67.80,2,3390.00,Shipped,1,1,2003,Vintage Cars,...,S18_2248,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Medium,2304 Long Airport Avenue unknown
2003-01-06,10100,22,86.51,4,1903.22,Shipped,1,1,2003,Vintage Cars,...,S18_4409,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-06,10100,49,34.47,1,1689.03,Shipped,1,1,2003,Vintage Cars,...,S24_3969,Online Diecast Creations Co.,6035558647,Nashua,62005,USA,Young,Valarie,Small,2304 Long Airport Avenue unknown
2003-01-09,10101,45,31.20,3,1404.00,Shipped,1,1,2003,Vintage Cars,...,S24_1937,"Blauer See Auto, Co.",+49 69 66 90 2555,Frankfurt,60528,Germany,Keitel,Roland,Small,Lyonerstr. 34 unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-05-31,10425,18,100.00,2,1895.94,In Process,2,5,2005,Trucks and Buses,...,S50_1392,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Small,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,33,100.00,4,4692.60,In Process,2,5,2005,Trucks and Buses,...,S12_4473,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10425,38,100.00,12,5894.94,In Process,2,5,2005,Classic Cars,...,S10_4962,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"
2005-05-31,10424,44,61.41,2,2702.04,In Process,2,5,2005,Trucks and Buses,...,S32_3522,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Small,"C/ Moralzarzal, 86 unknown"
2005-05-31,10425,38,99.41,7,3777.58,In Process,2,5,2005,Trucks and Buses,...,S18_2319,La Rochelle Gifts,40.67.8555,Nantes,44000,France,Labrune,Janine,Medium,"67, rue des Cinquante Otages unknown"

In [31]:
sales_data["PRICEEACH"].min()

26.88

In [32]:
sales_data["PRICEEACH"].max()

100.0

In [33]:
sales_data["PRICEEACH"].sum()

np.float64(236168.07)

In [34]:
sales_data["PRODUCTLINE"].unique()

array(['Vintage Cars', 'Trucks and Buses', 'Classic Cars', 'Trains',
       'Ships', 'Planes', 'Motorcycles'], dtype=object)

In [35]:
sales_data["PRODUCTLINE"].value_counts()

PRODUCTLINE
Classic Cars        967
Vintage Cars        607
Motorcycles         331
Planes              306
Trucks and Buses    301
Ships               234
Trains               77
Name: count, dtype: int64

In [37]:
train=sales_data[sales_data["PRODUCTLINE"]=="Trains"]
train

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,STATUS,QTR_ID,MONTH_ID,YEAR_ID,PRODUCTLINE,...,PRODUCTCODE,CUSTOMERNAME,PHONE,CITY,POSTALCODE,COUNTRY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,ADDRESS
ORDERDATE,,,,,,,,,,,,,,,,,,,,,
2003-01-31,10104,49,65.87,4,3227.63,Shipped,1,1,2003,Trains,...,S32_3207,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Medium,"C/ Moralzarzal, 86 unknown"
2003-01-31,10104,32,53.31,2,1705.92,Shipped,1,1,2003,Trains,...,S50_1514,Euro Shopping Channel,(91) 555 94 44,Madrid,28034,Spain,Freyre,Diego,Small,"C/ Moralzarzal, 86 unknown"
2003-02-11,10105,38,100.00,13,4330.10,Shipped,1,2,2003,Trains,...,S18_3259,Danish Wholesale Imports,31 12 3555,Kobenhavn,1734,Denmark,Petersen,Jytte,Medium,Vinb'ltet 34 unknown
2003-04-11,10116,27,63.38,1,1711.26,Shipped,2,4,2003,Trains,...,S32_3207,Royale Belge,(071) 23 67 2555,Charleroi,B-6000,Belgium,Cartrain,Pascale,Small,"Boulevard Tirou, 255 unknown"
2003-04-16,10117,21,49.21,11,1033.41,Shipped,2,4,2003,Trains,...,S50_1514,"Dragon Souveniers, Ltd.",+65 221 7555,Singapore,79903,Singapore,Natividad,Eric,Small,"Bronz Sok., Bronz Apt. 3/6 Tesvikiye unknown"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2005-03-17,10395,45,100.00,3,8977.05,Shipped,1,3,2005,Trains,...,S50_1514,Lyon Souveniers,+33 1 46 62 7555,Paris,75508,France,Da Cunha,Daniel,Large,27 rue du Colonel Pierre Avia unknown
2005-03-23,10396,24,89.75,4,2154.00,Shipped,1,3,2005,Trains,...,S18_3259,Mini Gifts Distributors Ltd.,4155551450,San Rafael,97562,USA,Nelson,Valarie,Small,5677 Strong St. unknown
2005-05-05,10413,24,49.71,6,1193.04,Shipped,2,5,2005,Trains,...,S32_3207,Gift Depot Inc.,2035552570,Bridgewater,97562,USA,King,Julie,Small,25593 South Bay Ln. unknown
2005-05-05,10413,51,63.85,4,3256.35,Shipped,2,5,2005,Trains,...,S50_1514,Gift Depot Inc.,2035552570,Bridgewater,97562,USA,King,Julie,Medium,25593 South Bay Ln. unknown
2005-05-06,10414,48,100.00,14,5808.48,On Hold,2,5,2005,Trains,...,S18_3259,Gifts4AllAges.com,6175559555,Boston,51003,USA,Yoshido,Juri,Medium,8616 Spinnaker Dr. unknown

In [38]:
cars = sales_data[(sales_data["PRODUCTLINE"]=="Vintage Cars")&(sales_data["STATUS"]=="Shipped")]

In [40]:
cars["STATUS"].value_counts()[0]

C:\Users\Rudra Pratap Singh\AppData\Local\Temp\ipykernel_19300\563497601.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  cars["STATUS"].value_counts()[0]

np.int64(557)

In [41]:
cars_det = cars[cars["STATUS"]=="Shipped"]
cars_det.shape[0]

557